# =============================================================================
# BUILD STAGE
# =============================================================================
FROM node:20-alpine AS builder

WORKDIR /app

# 1. Copy package files first (for layer caching)
COPY package*.json ./

# 2. Copy prisma schema BEFORE npm ci (postinstall runs prisma generate)
COPY prisma ./prisma/

# 3. Install all dependencies (dev + prod)
#    - postinstall script runs "prisma generate" automatically
RUN npm ci

# 4. Copy the rest of the source code
COPY . .

# 5. Build the Next.js application
#    - Uses output: 'standalone' from next.config.ts
#    - Creates .next/standalone with minimal node_modules
RUN npm run build

# =============================================================================
# PRODUCTION STAGE
# =============================================================================
FROM node:20-alpine AS runner

WORKDIR /app

# Set production environment
ENV NODE_ENV=production

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy built application from builder stage
# Order matters for Docker layer caching!

# 1. Public assets (static files)
COPY --from=builder /app/public ./public

# 2. Next.js standalone build (includes server.js and minimal dependencies)
COPY --from=builder /app/.next/standalone ./

# 3. Static assets generated by Next.js build
COPY --from=builder /app/.next/static ./.next/static

# 4. Prisma schema (needed for migrations in production)
COPY --from=builder /app/prisma ./prisma

# 5. Generated Prisma Client (the query engine)
#    This is the compiled client that talks to the database
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

# 6. Prisma client package (required alongside .prisma)
COPY --from=builder /app/node_modules/@prisma/client ./node_modules/@prisma/client

# 7. Package.json for prod:migrate script access
COPY --from=builder /app/package.json ./package.json

# Switch to non-root user
USER nextjs

# Expose the port Next.js runs on
EXPOSE 3000

# Environment variables for Next.js server
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create entrypoint script for migration + start
# Run migrations in production using 'prisma migrate deploy'
COPY --chown=nextjs:nodejs docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

# Entrypoint handles migration + server start
ENTRYPOINT ["/app/docker-entrypoint.sh"]
